baseURL = 'https://0x7d7b.github.io'
title = 'Henrik Sachse'
languageCode = 'en-us'
timeZone = 'Europe/Berlin'

theme = 'console-theme'

enableGitInfo = true
enableRobotsTXT = true

# Disable default taxonomies (categories, tags)
# See: https://gohugo.io/content-management/taxonomies/
disableKinds = ['taxonomy', 'term', 'section']

[markup.goldmark.renderer]
  # Insert <br/> on each CRLF in content.
  hardWraps = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    noHl = false
    tabWidth = 2


[params]
  author = 'Henrik Sachse'
  nick = "hs"
  description = 'Hi, my name is Henrik Sachse, I run this website.'
  mastodon = 'https://mastodon.social/@0x7d7b'

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[permalinks]
  posts = '/:year/:month/:title/'

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  page  = ["HTML"]
  taxonomy  = ["HTML"]
  term  = ["HTML"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
